# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  *
from checkXoGame import checkGame


class Ui_MainWindow(object):
    _pressType = "x"
    _gameCheck = [
        ["*", "*", "*"],
        ["*", "*", "*"],
        ["*", "*", "*"],
    ]


    def setupUi(self, MainWindow: QtWidgets.QMainWindow):
        MainWindow.setFixedSize(580, 580)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(120, 100, 100, 100))
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 100, 100, 100))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 100, 100, 100))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 220, 100, 100))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 220, 100, 100))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 220, 100, 100))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 340, 100, 100))
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(240, 340, 100, 100))
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(360, 340, 100, 100))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(240, 460, 93, 28))
        self.pushButton_10.setObjectName("pushButton_10")

        self.allButtons = [
                        self.pushButton_1,
                        self.pushButton_2,
                        self.pushButton_3,
                        self.pushButton_4,
                        self.pushButton_5,
                        self.pushButton_6,
                        self.pushButton_7,
                        self.pushButton_8,
                        self.pushButton_9
                    ]

        for item in self.allButtons:
            item.setStyleSheet("font-size: 40px")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.pushButton_1.clicked.connect(self.button1)
        self.pushButton_2.clicked.connect(self.button2)
        self.pushButton_3.clicked.connect(self.button3)
        self.pushButton_4.clicked.connect(self.button4)
        self.pushButton_5.clicked.connect(self.button5)
        self.pushButton_6.clicked.connect(self.button6)
        self.pushButton_7.clicked.connect(self.button7)
        self.pushButton_8.clicked.connect(self.button8)
        self.pushButton_9.clicked.connect(self.button9)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_10.setText(_translate("MainWindow", "New game"))


    def button1(self):
        self.pushButton_1.setText(self._pressType)
        self._gameCheck[0][0] = self._pressType
        if( self._pressType == "x" ): self._pressType = "o"
        else: self._pressType = "x"        
        self.pushButton_1.setEnabled(False)
        self.checkOurGame()

    def button2(self):
        self.pushButton_2.setText(self._pressType)
        self._gameCheck[0][1] = self._pressType
        if( self._pressType == "x" ): self._pressType = "o"
        else: self._pressType = "x"        
        self.pushButton_2.setEnabled(False)
        self.checkOurGame()

    def button3(self):
        self.pushButton_3.setText(self._pressType)
        self._gameCheck[0][2] = self._pressType
        if( self._pressType == "x" ): self._pressType = "o"
        else: self._pressType = "x"        
        self.pushButton_3.setEnabled(False)
        self.checkOurGame()

    def button4(self):
        self.pushButton_4.setText(self._pressType)
        self._gameCheck[1][0] = self._pressType
        if( self._pressType == "x" ): self._pressType = "o"
        else: self._pressType = "x"        
        self.pushButton_4.setEnabled(False)
        self.checkOurGame()

    def button5(self):
        self.pushButton_5.setText(self._pressType)
        self._gameCheck[1][1] = self._pressType
        if( self._pressType == "x" ): self._pressType = "o"
        else: self._pressType = "x"        
        self.pushButton_5.setEnabled(False)
        self.checkOurGame()

    def button6(self):
        self.pushButton_6.setText(self._pressType)
        self._gameCheck[1][2] = self._pressType
        if( self._pressType == "x" ): self._pressType = "o"
        else: self._pressType = "x"        
        self.pushButton_6.setEnabled(False)
        self.checkOurGame()

    def button7(self):
        self.pushButton_7.setText(self._pressType)
        self._gameCheck[2][0] = self._pressType
        if( self._pressType == "x" ): self._pressType = "o"
        else: self._pressType = "x"        
        self.pushButton_7.setEnabled(False)
        self.checkOurGame()

    def button8(self):
        self.pushButton_8.setText(self._pressType)
        self._gameCheck[2][1] = self._pressType
        if( self._pressType == "x" ): self._pressType = "o"
        else: self._pressType = "x"        
        self.pushButton_8.setEnabled(False)
        self.checkOurGame()

    def button9(self):
        self.pushButton_9.setText(self._pressType)
        self._gameCheck[2][2] = self._pressType
        if( self._pressType == "x" ): self._pressType = "o"
        else: self._pressType = "x"        
        self.pushButton_9.setEnabled(False)
        self.checkOurGame()


    def checkOurGame(self):
        if( checkGame(self._gameCheck) == "x" ):
            self.gameMessage("X yutdi")
        elif( checkGame(self._gameCheck) == "o" ):
            self.gameMessage("O yutdi")
        elif( checkGame(self._gameCheck) == "d" ):
            self.gameMessage("Durrang")
        # elif( checkGame(self._gameCheck) == "n" ):
        #     print("N")


    def gameMessage(self, message):
        msg = QMessageBox()
        msg.setText(message)
        msg.show()
        msg.exec()

        self.newGame()


    def newGame(self):
        for item in self.allButtons:
            item.setText("")
            item.setEnabled(True)

        self._pressType = "x"
        self._gameCheck = [
        ["*", "*", "*"],
        ["*", "*", "*"],
        ["*", "*", "*"],
    ]
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
